on:
  push:
    branches:
      - develop
  pull_request:
      types: [opened, synchronize, reopened]

env: # 统一设置环境变量
  SONARQUBE_URL: https://1n633k3337.zicp.fun
  REPO: pigeon
  BRANCH_NAME: develop
  LAN: javascript
  SOURCES: src
  REPO_URL: https://github.com/SunGg12138/yunxin-im.git

name: SonarQube Scan
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: params
      run: |
        echo "sender=$GITHUB_ACTOR" >> $GITHUB_ENV
        echo "commitHash=$GITHUB_SHA" >> $GITHUB_ENV
        echo "packageName=$REPO" >> $GITHUB_ENV
        echo "branchName=$BRANCH_NAME" >> $GITHUB_ENV
        echo "baseUrl=$SONARQUBE_URL" >> $GITHUB_ENV
        echo "language=$LAN" >> $GITHUB_ENV
        echo "sources=$SOURCES" >> $GITHUB_ENV
        echo "repoUrl=$REPO_URL" >> $GITHUB_ENV
    - name: full url
      run: |
         echo "fullUrl=${{ env.baseUrl }}/api/sonarqube/scan?packageName=${{ env.packageName }}&branchName=${{ env.branchName }}&username=${{ env.sender }}&commit=${{ env.commitHash }}&language=${{ env.language }}&sources=${{ env.sources }}&repoUrl=${{ env.repoUrl }}" >> $GITHUB_ENV
    - name: curl
      run:  |
        echo ${{ env.fullUrl }}
        curl --location "${{ env.fullUrl }}"
