on:
  push:
    branches:
      - develop
  pull_request:
      types: [opened, synchronize, reopened]

env: # 统一设置环境变量
  SONARQUBE_URL: https://5940cq2570.zicp.fun
  REPO: pigeon
  BRANCH_NAME: develop
  GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")

name: SonarQube Scan
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: curl
      uses: indiesdev/curl@v1.1
      with: 
        url: ${SONARQUBE_URL}/api/sonarqube/scan?packageName=${REPO}&branchName=${BRANCH_NAME}&username=${GITHUB_ACTOR}&commit=${GIT_HASH}&language=javascript&sources=src
        method: GET
        
