on:
  push:
    branches:
      - develop
  pull_request:
      types: [opened, synchronize, reopened]

env: # 统一设置环境变量
  SONARQUBE_URL: https://1n633k3337.zicp.fun
  REPO: pigeon
  BRANCH_NAME: develop
  GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")

name: SonarQube Scan
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: curl
      run:  |
        echo $SONARQUBE_URL/api/sonarqube/scan?packageName=${{ REPO }}&branchName=${{ BRANCH_NAME }}&username=${{ GITHUB_ACTOR }}&commit=${{ GIT_HASH }}&language=javascript&sources=src
        curl --location $SONARQUBE_URL/api/sonarqube/scan?packageName=$REPO&branchName=$BRANCH_NAME&username=$GITHUB_ACTOR&commit=$GIT_HASH&language=javascript&sources=src
