on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

env: # 统一设置环境变量
  GIT_USER: git
  GIT_EMAIL: email@example.com
  THEME_REPO: git/next
  DEPLOY_REPO: git/gagahappy.github.io

name: SonarQube Scan
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.3
      - name: npm install
        run: npm install sonarqube-scanner
      - name: SonarQube Scan
        run: node sonar.js
