on: 
  pull_request:
    branches:    
      - develop
      - master

env: # 统一设置环境变量
  WEBHOOK: https://open.feishu.cn/open-apis/bot/v2/hook/5e72d42e-833f-484d-b3c0-433b02e9f417

name: Pull-Request 
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: params
      run: |
        echo "sender=$GITHUB_ACTOR" >> $GITHUB_ENV
        echo "webhook=$WEBHOOK" >> $GITHUB_ENV
        echo "repo=$GITHUB_REPOSITORY" >> $GITHUB_ENV
    - name: curl
      run:  |
        curl --location '${{env.WEBHOOK}}' --header 'Content-Type: application/json' --data '{"msg_type":"interactive","card":{"type":"template","data":{"template_id":"ctp_AArtbiseKiiY","template_variable":{"commitSha":"${{env.repo}}","startCommitSha":"${{env.sender}}","jump_url":"${{ github.event.pull_request.head.ref }}","new_bugs":"${{ github.event.pull_request.base.ref }}","new_vulnerabilities":"${{github.repository}}","new_security_hotspots":"1111","new_code_smells":"1111","new_bugs_color":"green","new_vulnerabilities_color":"green","new_security_hotspots_color":"green","new_code_smells_color":"green"}}}}'
