on: 
  pull_request:
    branches:    
      - develop

env: # 统一设置环境变量
  WEBHOOK: https://open.feishu.cn/open-apis/bot/v2/hook/5e72d42e-833f-484d-b3c0-433b02e9f417

name: Pull Request Event
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: params
      run: |
        echo "sender=$GITHUB_ACTOR" >> $GITHUB_ENV
        echo "webhook=$WEBHOOK" >> $GITHUB_ENV
        echo "repo=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
    - name: curl
      run:  |
        curl --location '${{env.WEBHOOK}}' --header 'Content-Type: application/json' --data '{"msg_type":"interactive","card":{"type":"template","data":{"template_id":"ctp_AAm2sd6ncekB","template_variable":{"repo":"${{env.repo}}","headBranch":"${{github.event.pull_request.head.ref}}","actor":"${{github.actor}}","jump_url":"${{ github.event.pull_request.html_url }}"}}}}'
